// <auto-generated />
namespace WebApplication.BL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addDefaultValue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDefaultValue));
        
        string IMigrationMetadata.Id
        {
            get { return "202405261631389_addDefaultValue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
