// <auto-generated />
namespace WebApplication.BL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<<< HEAD:WebApplication.BL/Migrations/202405291151046_AddImageP.Designer.cs
    public sealed partial class AddImageP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddImageP));
        
        string IMigrationMetadata.Id
        {
            get { return "202405291151046_AddImageP"; }
========
    public sealed partial class listOfProducts29 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(listOfProducts29));
        
        string IMigrationMetadata.Id
        {
            get { return "202405281417343_listOfProducts29"; }
>>>>>>>> ccbb4086024f4c54df2ebced8680a6eab80365a2:WebApplication.BL/Migrations/202405281417343_listOfProducts29.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
