// <auto-generated />
namespace WebApplication.BL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class wishlistEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wishlistEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "202405261840082_wishlistEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
